spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/development/h2/jpa1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # LAZY 로딩 시 한 번에 조회해올 개수

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
