spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/development/h2/jpa1  # H2 1.4.200 ???? MVCC ??? ???. (1.4.
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true # sysout ?? ?? ???, ?? ?? ??? ?? ?? ??.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # hibernate? ???? SQL? ?? debug ??? ? ? ??. logger? ?? ???? ?.
    org.hibernate.type: trace
